collections:

  - name: ansible.windows
    source: https://towerhub.shadowman.dev/api/galaxy/content/community/

  - name: community.windows
    source: https://towerhub.shadowman.dev/api/galaxy/content/community/

  - name: ansible.posix
  