---
- name: Open Firewalld for apache
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled 
  notify: restart_firewalld

- name: Open Firewalld for SSL
  ansible.posix.firewalld:
    service: https
    permanent: yes
    state: enabled
  notify: restart_firewalld

- name: Add apache and SSL package for RHEL 7
  ansible.builtin.yum:
    name: 
      - httpd
      - mod_ssl
    state: latest
  notify: httpd_running
  when: os is match("rhel_7.*") or os is match ("rhel7.*")
  
- name: Add apache and SSL package for RHEL 8
  ansible.builtin.dnf:
    name: 
      - httpd
      - mod_ssl
    state: latest
  notify: httpd_running
  when: os is match("rhel_8.*") or os is match ("rhel8.*")

- name: Copy website formatting
  ansible.builtin.copy:
    src: website/
    dest: /var/www/html/

- name: Copy Cert
  ansible.builtin.copy:
    src: /certs/shadowman_cert.cer
    dest: /etc/pki/tls/certs/localhost.crt
  delegate_to: aap.shadowman.dev
  
- name: Copy Key
  ansible.builtin.copy:
    src: /certs/shadowman_private.key
    dest: /etc/pki/tls/private/localhost.key
  delegate_to: aap.shadowman.dev

- name: Insert Index Page for webpage
  ansible.builtin.template:
    src: templates/indexcomplex.html.j2
    dest: /var/www/html/index.html
  tags:
    - updaterhel
