---
- include_tasks: rhel_apache_collections.yml
  when: os is match("rhel.*")
  tags:
      - updaterhel

- include_tasks: windows_iis_collections.yml
  when: os is match("windows.*")
  tags:
      - updatewin