---
- name: Open Firewalld for apache
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled 
  notify: restart_firewalld

- name: Open Firewalld for SSL
  ansible.posix.firewalld:
    service: https
    permanent: yes
    state: enabled
  notify: restart_firewalld

- name: Add apache and SSL package for RHEL 7
  ansible.builtin.yum:
    name: 
      - httpd
      - mod_ssl
    state: latest
  notify: httpd_running
  when: os is match("rhel.*7.*") or os is match ("rhel7.*")
  
- name: Add apache and SSL package for RHEL 8
  ansible.builtin.dnf:
    name: 
      - httpd
      - mod_ssl
    state: latest
  notify: httpd_running
  when: os is match("rhel.*8.*") or os is match ("rhel8.*")

- name: Copy website formatting
  ansible.builtin.copy:
    src: website/
    dest: /var/www/html/

- name: Fetch cert
  ansible.builtin.fetch:
    src: /certs/shadowman_cert.cer
    dest: /tmp/certs/shadowman_cert.cer
    flat: yes
  delegate_to: aap.shadowman.dev

- name: Copy Cert
  ansible.builtin.copy:
    src: /tmp/certs/shadowman_cert.cer
    dest: /etc/pki/tls/certs/localhost.crt

- name: Fetch key
  ansible.builtin.fetch:
    src: /certs/shadowman_private.key
    dest: /tmp/certs/shadowman_private.key
    flat: yes
  delegate_to: aap.shadowman.dev
  
- name: Copy Key
  ansible.builtin.copy:
    src: /tmp/certs/shadowman_private.key
    dest: /etc/pki/tls/private/localhost.key

- name: Insert Index Page for webpage
  ansible.builtin.template:
    src: templates/indexcomplex.html.j2
    dest: /var/www/html/index.html
  tags:
    - updaterhel
